skippedProviders:
  # - ReadmeCheck
  # - LicenseCheck
  # - SwiftLintCheck

projectRootAppendix: Null

swiftLintConfig:
  lintingRulesPath: https://raw.githubusercontent.com/JulianKahnert/chia-config/master/.swiftlint.yml

spellCheckConfig:
  # onlyLatestFiles: False
  ignoredPaths:
    - vendor
    - .build
    - .swiftpm
  ignoredWords:
    - __bill_ikea_iot
    - _tagname
    - abschlagbehälter
    - analyze
    - analyzed
    - analyzes
    - anstellgut
    - anstellguts
    - apfelot
    - appicon-pdfarchiveviewer.svg
    - appicon.svg
    - appstore-lrg.svg
    - atom.io
    - backt-mehr-brot
    - bigimg
    - brewista
    - btsync
    - checkprovider
    - chia.yml
    - chrisaljoudi
    - christianelies.de
    - chsh
    - config.xcconfig
    - contributing.md
    - cre213-brot
    - crelies
    - ct
    - cyclomatic_complexity
    - descriptionword
    - discord.pdf-archiver.io
    - display:inline-block;overflow:hidden;background:url
    - dotfiles
    - durchflusszeit
    - eduardosanchez.me
    - einkreiser
    - emphasize
    - erdgeist.org
    - espresso-maschinenraum.de
    - espressomaschine
    - espressotasse
    - espressoxxl
    - ezjail
    - faq
    - feedbin
    - frameborder
    - gebacken-konsumbrot
    - github
    - gp
    - gpio
    - hancoffee
    - home-assistant.io
    - ifun
    - ikea-tradfri-gateway
    - initialization
    - initialized
    - ios.pdf-archiver.io
    - itunes_store
    - janw.io
    - johnsundell
    - juliankahnert
    - kaffeefettreiniger
    - kaffeewiki
    - karl-voit.at
    - lelit
    - linkmaker.itunes.apple.com
    - lintingrulespath
    - localized
    - lz4
    - macos.pdf-archiver.io
    - mahlgradeinstellungen
    - milchaufschäumen
    - minkorrekt-21
    - moldvaer
    - mounten
    - mqtt
    - msp
    - mt
    - myflavour
    - mypool
    - nachkommastelle
    - no-repeat;width:135px;height:40px
    - ntpd
    - ntpdate
    - ntpq
    - octocat
    - pdf-archiver
    - pdf-archiver-deutlich-verbessert-und-mit-symbolischem-abo-preis-124604
    - pdf-archiver-open-source-projekt-zur-langzeit-archivierung-119547
    - pdf-archiver.io
    - pdfarchiver
    - ploetzblog
    - pool.ntp.org
    - puly
    - raspberrypi
    - raw.githubusercontent.com
    - resolv.conf
    - recalibrating-baratza-vario-t10282.html
    - roggenvollkornmehl
    - sauerteig
    - scanbot
    - searchterm
    - searchword
    - sentry.io
    - serializing
    - siebträgermaschine
    - siebträgermaschinen
    - skstorereviewcontroller
    - stackoverflow.com
    - standardized
    - storekit
    - süpke
    - swiftlint
    - swiftystorekit
    - sysutils
    - testflight
    - triosence
    - tsantidis
    - tschunk
    - uicolor.swift
    - vimeo
    - visudo
    - wechselberger
    - wwdc2019
    - www.backblaze.com
    - www.baratza.com
    - www.raywenderlich.com
    - xcconfig
    - xing
    - yml
    - yonaskolb
    - zfs
    - zfstools
    - zpool
    - zutatenmenge
    - zweikreiser
