name: Deploy with Publish

on:
  push:
    branches:
    - author

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and run chia
      run: |
        # TODO: download chia binary directly would improve build times
        git clone https://github.com/worldiety/chia 
        cd chia
        swift build --configuration release
        mv `swift build --configuration release --show-bin-path`/chia /usr/local/bin
        cd ..
        rm -rf chia/
        /usr/local/bin/chia --config .chia.yml

    - name: Build Publish
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - name: Build the site with Publish
      run: |
        publish generate

    # - name: Move files to 'page' folder
    #   run: mkdir page && cp -R _site/* page/ && cp CNAME page/ && touch page/.nojekyll && cp -r .well-known page/

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main # The branch the action should deploy to.
        FOLDER: Output # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch

    - name: Purge cache
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}