name: Deploy with Publish

on:
  push:
    branches:
      - author

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run chia
        run: |
          # TODO: download chia binary directly would improve build times
          git clone https://github.com/JulianKahnert/chia 
          cd chia
          swift build --configuration release
          mv `swift build --configuration release --show-bin-path`/chia /usr/local/bin
          cd ..
          rm -rf chia/
          /usr/local/bin/chia --config .chia.yml

  build:
    runs-on: ubuntu-latest
    container:
      image: "swift:5.4"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Publish
        run: |
          git clone https://github.com/JohnSundell/Publish.git
          cd Publish
          make

      - name: Generate Site
        run: publish generate

      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.

        uses: actions/upload-artifact@v2
        with:
          name: site
          path: Output

  deploy:
    needs: [validate, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3.0.0

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v2
        with:
          name: site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          folder: .
          branch: main

  purge-cache:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Purge cache
        uses: nathanvaughn/actions-cloudflare-purge@master
        if: success()
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
